from django.urls import path
from project.mobboss_apps.gameplay import views

urlpatterns = [
    path("game-info/", views.game_info, name="gameplay-game-info"),
    path("<str:game_id>/", views.detail, name="gameplay-detail"),
    path("<str:game_id>/exit", views.exit_game, name="gameplay-exit"),
    path("<str:game_id>/report-death", views.report_death, name="gameplay-report-death"),
    path("<str:game_id>/advance-accused-selection-timeout", views.advance_accused_selection_timeout, name="gameplay-advance-accused-selection-timeout"),
    path("<str:game_id>/submit-accused-selection", views.submit_accused_selection, name="gameplay-submit-accused-selection"),
    path(
        "<str:game_id>/submit-trial-vote",
        views.submit_trial_vote,
        name="gameplay-submit-trial-vote",
    ),
    path(
        "<str:game_id>/start-trial-voting",
        views.start_trial_voting,
        name="gameplay-start-trial-voting",
    ),
    path(
        "<str:game_id>/activate-don-silence",
        views.activate_don_silence,
        name="gameplay-activate-don-silence",
    ),
    path(
        "<str:game_id>/activate-underboss-jury-override",
        views.activate_underboss_jury_override,
        name="gameplay-activate-underboss-jury-override",
    ),
    path(
        "<str:game_id>/activate-kingpin-reduce-clock",
        views.activate_kingpin_reduce_clock,
        name="gameplay-activate-kingpin-reduce-clock",
    ),
    path(
        "<str:game_id>/activate-gangster-tamper",
        views.activate_gangster_tamper,
        name="gameplay-activate-gangster-tamper",
    ),
    path(
        "<str:game_id>/activate-street-thug-steal",
        views.activate_street_thug_steal,
        name="gameplay-activate-street-thug-steal",
    ),
    path(
        "<str:game_id>/activate-deputy-protective-custody",
        views.activate_deputy_protective_custody,
        name="gameplay-activate-deputy-protective-custody",
    ),
    path(
        "<str:game_id>/activate-sheriff-view-jury-log",
        views.activate_sheriff_view_jury_log,
        name="gameplay-activate-sheriff-view-jury-log",
    ),
    path(
        "<str:game_id>/activate-captain-asset-freeze",
        views.activate_captain_asset_freeze,
        name="gameplay-activate-captain-asset-freeze",
    ),
    path(
        "<str:game_id>/activate-lieutenant-information-briefcase",
        views.activate_lieutenant_information_briefcase,
        name="gameplay-activate-lieutenant-information-briefcase",
    ),
    path(
        "<str:game_id>/activate-sergeant-capture",
        views.activate_sergeant_capture,
        name="gameplay-activate-sergeant-capture",
    ),
    path(
        "<str:game_id>/activate-detective-investigation",
        views.activate_detective_investigation,
        name="gameplay-activate-detective-investigation",
    ),
    path(
        "<str:game_id>/activate-smuggler-smuggle",
        views.activate_smuggler_smuggle,
        name="gameplay-activate-smuggler-smuggle",
    ),
    path(
        "<str:game_id>/activate-gun-runner-charisma",
        views.activate_gun_runner_charisma,
        name="gameplay-activate-gun-runner-charisma",
    ),
    path(
        "<str:game_id>/activate-supplier-acquire",
        views.activate_supplier_acquire,
        name="gameplay-activate-supplier-acquire",
    ),
    path(
        "<str:game_id>/activate-inspector-record-inspection",
        views.activate_inspector_record_inspection,
        name="gameplay-activate-inspector-record-inspection",
    ),
    path(
        "<str:game_id>/activate-police-officer-confiscation",
        views.activate_police_officer_confiscation,
        name="gameplay-activate-police-officer-confiscation",
    ),
    path(
        "<str:game_id>/activate-made-man-skip-middle-man",
        views.activate_made_man_skip_middle_man,
        name="gameplay-activate-made-man-skip-middle-man",
    ),
    path(
        "<str:game_id>/activate-merchant-wholesale-order",
        views.activate_merchant_wholesale_order,
        name="gameplay-activate-merchant-wholesale-order",
    ),
    path(
        "<str:game_id>/buy-from-supply",
        views.buy_from_supply,
        name="gameplay-buy-from-supply",
    ),
    path(
        "<str:game_id>/set-inventory-resale-price",
        views.set_inventory_resale_price,
        name="gameplay-set-inventory-resale-price",
    ),
    path(
        "<str:game_id>/sell-inventory-item",
        views.sell_inventory_item,
        name="gameplay-sell-inventory-item",
    ),
    path(
        "<str:game_id>/sell-inventory-to-supply",
        views.sell_inventory_to_supply,
        name="gameplay-sell-inventory-to-supply",
    ),
    path(
        "<str:game_id>/offer-gift-item",
        views.offer_gift_item,
        name="gameplay-offer-gift-item",
    ),
    path(
        "<str:game_id>/give-money",
        views.give_money,
        name="gameplay-give-money",
    ),
    path(
        "<str:game_id>/respond-money-gift-offer",
        views.respond_money_gift_offer,
        name="gameplay-respond-money-gift-offer",
    ),
    path(
        "<str:game_id>/respond-gift-offer",
        views.respond_gift_offer,
        name="gameplay-respond-gift-offer",
    ),
    path(
        "<str:game_id>/respond-sale-offer",
        views.respond_sale_offer,
        name="gameplay-respond-sale-offer",
    ),
]
