"""Authoritative starting money table keyed by player count and role name."""

from __future__ import annotations

MIN_SUPPORTED_PLAYER_COUNT = 7
MAX_SUPPORTED_PLAYER_COUNT = 25

STARTING_MONEY_BY_PLAYER_COUNT: dict[int, dict[str, int]] = {
    7: {
        "Chief of Police": 240,
        "Deputy": 150,
        "Sheriff": 90,
        "Captain": 80,
        "Lieutenant": 70,
        "Sergeant": 70,
        "Detective": 60,
        "Inspector": 60,
        "Police Officer": 50,
        "Cop": 60,
        "Mob Boss": 80,
        "Don": 50,
        "Under Boss": 40,
        "Kingpin": 40,
        "Enforcer": 30,
        "Made Man": 30,
        "Gangster": 20,
        "Street Thug": 20,
        "Felon": 20,
        "Knife Hobo": 0,
        "Merchant": 240,
        "Arms Dealer": 140,
        "Smuggler": 140,
        "Gun Runner": 140,
        "Supplier": 140,
    },
    8: {
        "Chief of Police": 210,
        "Deputy": 140,
        "Sheriff": 90,
        "Captain": 80,
        "Lieutenant": 80,
        "Sergeant": 80,
        "Detective": 70,
        "Inspector": 70,
        "Police Officer": 60,
        "Cop": 60,
        "Mob Boss": 90,
        "Don": 60,
        "Under Boss": 50,
        "Kingpin": 50,
        "Enforcer": 30,
        "Made Man": 30,
        "Gangster": 20,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 260,
        "Arms Dealer": 160,
        "Smuggler": 160,
        "Gun Runner": 160,
        "Supplier": 160,
    },
    9: {
        "Chief of Police": 240,
        "Deputy": 150,
        "Sheriff": 100,
        "Captain": 90,
        "Lieutenant": 90,
        "Sergeant": 90,
        "Detective": 80,
        "Inspector": 80,
        "Police Officer": 60,
        "Cop": 60,
        "Mob Boss": 70,
        "Don": 60,
        "Under Boss": 50,
        "Kingpin": 50,
        "Enforcer": 30,
        "Made Man": 30,
        "Gangster": 20,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 280,
        "Arms Dealer": 180,
        "Smuggler": 180,
        "Gun Runner": 180,
        "Supplier": 180,
    },
    10: {
        "Chief of Police": 210,
        "Deputy": 110,
        "Sheriff": 100,
        "Captain": 90,
        "Lieutenant": 90,
        "Sergeant": 90,
        "Detective": 80,
        "Inspector": 80,
        "Police Officer": 60,
        "Cop": 60,
        "Mob Boss": 100,
        "Don": 60,
        "Under Boss": 50,
        "Kingpin": 50,
        "Enforcer": 30,
        "Made Man": 30,
        "Gangster": 30,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 280,
        "Arms Dealer": 180,
        "Smuggler": 180,
        "Gun Runner": 180,
        "Supplier": 180,
    },
    11: {
        "Chief of Police": 200,
        "Deputy": 100,
        "Sheriff": 100,
        "Captain": 80,
        "Lieutenant": 80,
        "Sergeant": 80,
        "Detective": 80,
        "Inspector": 80,
        "Police Officer": 70,
        "Cop": 60,
        "Mob Boss": 100,
        "Don": 60,
        "Under Boss": 50,
        "Kingpin": 50,
        "Enforcer": 40,
        "Made Man": 40,
        "Gangster": 30,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 290,
        "Arms Dealer": 190,
        "Smuggler": 190,
        "Gun Runner": 190,
        "Supplier": 190,
    },
    12: {
        "Chief of Police": 200,
        "Deputy": 100,
        "Sheriff": 100,
        "Captain": 90,
        "Lieutenant": 80,
        "Sergeant": 80,
        "Detective": 80,
        "Inspector": 80,
        "Police Officer": 70,
        "Cop": 70,
        "Mob Boss": 100,
        "Don": 70,
        "Under Boss": 60,
        "Kingpin": 60,
        "Enforcer": 50,
        "Made Man": 50,
        "Gangster": 40,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 290,
        "Arms Dealer": 190,
        "Smuggler": 190,
        "Gun Runner": 190,
        "Supplier": 190,
    },
    13: {
        "Chief of Police": 240,
        "Deputy": 120,
        "Sheriff": 90,
        "Captain": 80,
        "Lieutenant": 70,
        "Sergeant": 70,
        "Detective": 70,
        "Inspector": 70,
        "Police Officer": 70,
        "Cop": 70,
        "Mob Boss": 90,
        "Don": 60,
        "Under Boss": 50,
        "Kingpin": 50,
        "Enforcer": 40,
        "Made Man": 40,
        "Gangster": 30,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 330,
        "Arms Dealer": 230,
        "Smuggler": 230,
        "Gun Runner": 230,
        "Supplier": 230,
    },
    14: {
        "Chief of Police": 250,
        "Deputy": 120,
        "Sheriff": 90,
        "Captain": 90,
        "Lieutenant": 80,
        "Sergeant": 80,
        "Detective": 70,
        "Inspector": 70,
        "Police Officer": 70,
        "Cop": 70,
        "Mob Boss": 90,
        "Don": 70,
        "Under Boss": 60,
        "Kingpin": 60,
        "Enforcer": 50,
        "Made Man": 50,
        "Gangster": 40,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 260,
        "Arms Dealer": 160,
        "Smuggler": 160,
        "Gun Runner": 160,
        "Supplier": 160,
    },
    15: {
        "Chief of Police": 250,
        "Deputy": 130,
        "Sheriff": 90,
        "Captain": 90,
        "Lieutenant": 90,
        "Sergeant": 90,
        "Detective": 80,
        "Inspector": 80,
        "Police Officer": 80,
        "Cop": 80,
        "Mob Boss": 100,
        "Don": 70,
        "Under Boss": 60,
        "Kingpin": 60,
        "Enforcer": 50,
        "Made Man": 50,
        "Gangster": 40,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 280,
        "Arms Dealer": 180,
        "Smuggler": 180,
        "Gun Runner": 180,
        "Supplier": 180,
    },
    16: {
        "Chief of Police": 240,
        "Deputy": 130,
        "Sheriff": 100,
        "Captain": 90,
        "Lieutenant": 90,
        "Sergeant": 90,
        "Detective": 90,
        "Inspector": 90,
        "Police Officer": 80,
        "Cop": 80,
        "Mob Boss": 100,
        "Don": 70,
        "Under Boss": 60,
        "Kingpin": 60,
        "Enforcer": 50,
        "Made Man": 50,
        "Gangster": 40,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 290,
        "Arms Dealer": 190,
        "Smuggler": 190,
        "Gun Runner": 190,
        "Supplier": 190,
    },
    17: {
        "Chief of Police": 210,
        "Deputy": 140,
        "Sheriff": 100,
        "Captain": 100,
        "Lieutenant": 100,
        "Sergeant": 100,
        "Detective": 90,
        "Inspector": 90,
        "Police Officer": 80,
        "Cop": 80,
        "Mob Boss": 100,
        "Don": 80,
        "Under Boss": 70,
        "Kingpin": 70,
        "Enforcer": 60,
        "Made Man": 60,
        "Gangster": 50,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 300,
        "Arms Dealer": 200,
        "Smuggler": 200,
        "Gun Runner": 200,
        "Supplier": 200,
    },
    18: {
        "Chief of Police": 200,
        "Deputy": 140,
        "Sheriff": 100,
        "Captain": 100,
        "Lieutenant": 100,
        "Sergeant": 100,
        "Detective": 100,
        "Inspector": 100,
        "Police Officer": 80,
        "Cop": 80,
        "Mob Boss": 100,
        "Don": 80,
        "Under Boss": 70,
        "Kingpin": 70,
        "Enforcer": 60,
        "Made Man": 60,
        "Gangster": 50,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 260,
        "Arms Dealer": 160,
        "Smuggler": 160,
        "Gun Runner": 160,
        "Supplier": 160,
    },
    19: {
        "Chief of Police": 200,
        "Deputy": 130,
        "Sheriff": 100,
        "Captain": 100,
        "Lieutenant": 90,
        "Sergeant": 90,
        "Detective": 90,
        "Inspector": 90,
        "Police Officer": 80,
        "Cop": 80,
        "Mob Boss": 100,
        "Don": 80,
        "Under Boss": 70,
        "Kingpin": 70,
        "Enforcer": 60,
        "Made Man": 60,
        "Gangster": 50,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 270,
        "Arms Dealer": 170,
        "Smuggler": 170,
        "Gun Runner": 170,
        "Supplier": 170,
    },
    20: {
        "Chief of Police": 200,
        "Deputy": 130,
        "Sheriff": 100,
        "Captain": 100,
        "Lieutenant": 90,
        "Sergeant": 90,
        "Detective": 90,
        "Inspector": 90,
        "Police Officer": 80,
        "Cop": 80,
        "Mob Boss": 100,
        "Don": 80,
        "Under Boss": 70,
        "Kingpin": 70,
        "Enforcer": 60,
        "Made Man": 60,
        "Gangster": 50,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 280,
        "Arms Dealer": 180,
        "Smuggler": 180,
        "Gun Runner": 180,
        "Supplier": 180,
    },
    21: {
        "Chief of Police": 200,
        "Deputy": 130,
        "Sheriff": 100,
        "Captain": 90,
        "Lieutenant": 90,
        "Sergeant": 90,
        "Detective": 80,
        "Inspector": 80,
        "Police Officer": 80,
        "Cop": 80,
        "Mob Boss": 100,
        "Don": 70,
        "Under Boss": 60,
        "Kingpin": 60,
        "Enforcer": 50,
        "Made Man": 50,
        "Gangster": 40,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 280,
        "Arms Dealer": 180,
        "Smuggler": 180,
        "Gun Runner": 180,
        "Supplier": 180,
    },
    22: {
        "Chief of Police": 240,
        "Deputy": 150,
        "Sheriff": 90,
        "Captain": 80,
        "Lieutenant": 70,
        "Sergeant": 70,
        "Detective": 70,
        "Inspector": 70,
        "Police Officer": 70,
        "Cop": 70,
        "Mob Boss": 90,
        "Don": 60,
        "Under Boss": 50,
        "Kingpin": 50,
        "Enforcer": 40,
        "Made Man": 40,
        "Gangster": 30,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 250,
        "Arms Dealer": 150,
        "Smuggler": 150,
        "Gun Runner": 150,
        "Supplier": 150,
    },
    23: {
        "Chief of Police": 250,
        "Deputy": 150,
        "Sheriff": 90,
        "Captain": 90,
        "Lieutenant": 80,
        "Sergeant": 80,
        "Detective": 70,
        "Inspector": 70,
        "Police Officer": 70,
        "Cop": 70,
        "Mob Boss": 90,
        "Don": 70,
        "Under Boss": 60,
        "Kingpin": 60,
        "Enforcer": 50,
        "Made Man": 50,
        "Gangster": 40,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 260,
        "Arms Dealer": 160,
        "Smuggler": 160,
        "Gun Runner": 160,
        "Supplier": 160,
    },
    24: {
        "Chief of Police": 250,
        "Deputy": 130,
        "Sheriff": 90,
        "Captain": 90,
        "Lieutenant": 90,
        "Sergeant": 90,
        "Detective": 80,
        "Inspector": 80,
        "Police Officer": 80,
        "Cop": 80,
        "Mob Boss": 100,
        "Don": 70,
        "Under Boss": 60,
        "Kingpin": 60,
        "Enforcer": 50,
        "Made Man": 50,
        "Gangster": 40,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 270,
        "Arms Dealer": 170,
        "Smuggler": 170,
        "Gun Runner": 170,
        "Supplier": 170,
    },
    25: {
        "Chief of Police": 250,
        "Deputy": 130,
        "Sheriff": 90,
        "Captain": 90,
        "Lieutenant": 90,
        "Sergeant": 90,
        "Detective": 80,
        "Inspector": 80,
        "Police Officer": 80,
        "Cop": 80,
        "Mob Boss": 100,
        "Don": 70,
        "Under Boss": 60,
        "Kingpin": 60,
        "Enforcer": 50,
        "Made Man": 50,
        "Gangster": 40,
        "Street Thug": 20,
        "Felon": 10,
        "Knife Hobo": 0,
        "Merchant": 280,
        "Arms Dealer": 180,
        "Smuggler": 180,
        "Gun Runner": 180,
        "Supplier": 180,
    },
}

_SUPPORTED_ROLE_NAMES: tuple[str, ...] = tuple(STARTING_MONEY_BY_PLAYER_COUNT[MIN_SUPPORTED_PLAYER_COUNT].keys())


def getStartingMoney(playerCount: int, roleName: str) -> int:
    """Return starting money for a role at a given player count."""
    if isinstance(playerCount, bool):
        raise ValueError("playerCount must be an integer from 7 to 25.")
    try:
        normalized_player_count = int(playerCount)
    except (TypeError, ValueError) as exc:
        raise ValueError("playerCount must be an integer from 7 to 25.") from exc

    if normalized_player_count < MIN_SUPPORTED_PLAYER_COUNT or normalized_player_count > MAX_SUPPORTED_PLAYER_COUNT:
        raise ValueError(
            f"Unsupported playerCount {normalized_player_count}. Expected {MIN_SUPPORTED_PLAYER_COUNT}-{MAX_SUPPORTED_PLAYER_COUNT}."
        )

    role_name = str(roleName).strip()
    if not role_name:
        raise ValueError("roleName is required.")

    balance_by_role = STARTING_MONEY_BY_PLAYER_COUNT[normalized_player_count]
    if role_name not in balance_by_role:
        allowed_roles = ", ".join(_SUPPORTED_ROLE_NAMES)
        raise ValueError(f"Unsupported roleName '{role_name}'. Expected one of: {allowed_roles}.")

    return int(balance_by_role[role_name])


def get_starting_money(player_count: int, role_name: str) -> int:
    """Snake-case alias for getStartingMoney."""
    return getStartingMoney(player_count, role_name)
